name: flutter_faculdade
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.5
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  flutter_svg_icons: ^0.0.1+4
  carousel_slider: ^5.0.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  getwidget: ^4.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  freezed: ^3.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/


flutter_native_splash:
  color: "#673AB7"
  image: assets/komanda.png
  android: true
  ios: true