// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC06WQvVJ33RXEP0NaXX4o6GxDMOYwqx7c',
    appId: '1:997803267726:web:ce5ff8c954092ce888dbdf',
    messagingSenderId: '997803267726',
    projectId: 'comanda-digital-5dbae',
    authDomain: 'comanda-digital-5dbae.firebaseapp.com',
    storageBucket: 'comanda-digital-5dbae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYZmpZhREurpKTNlvsIZmu5QC3JWMRHlw',
    appId: '1:997803267726:android:2f7b2975bd49220c88dbdf',
    messagingSenderId: '997803267726',
    projectId: 'comanda-digital-5dbae',
    storageBucket: 'comanda-digital-5dbae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxu4NUycMSoTwpkV0eE8QcnQcHfdZhsQw',
    appId: '1:997803267726:ios:f5f4f81c25f9b6c088dbdf',
    messagingSenderId: '997803267726',
    projectId: 'comanda-digital-5dbae',
    storageBucket: 'comanda-digital-5dbae.firebasestorage.app',
    iosBundleId: 'com.atilarodrigues.flutterFaculdade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxu4NUycMSoTwpkV0eE8QcnQcHfdZhsQw',
    appId: '1:997803267726:ios:9dcb19e526388a5088dbdf',
    messagingSenderId: '997803267726',
    projectId: 'comanda-digital-5dbae',
    storageBucket: 'comanda-digital-5dbae.firebasestorage.app',
    iosBundleId: 'com.example.flutterFaculdade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC06WQvVJ33RXEP0NaXX4o6GxDMOYwqx7c',
    appId: '1:997803267726:web:697ad822c5567c1688dbdf',
    messagingSenderId: '997803267726',
    projectId: 'comanda-digital-5dbae',
    authDomain: 'comanda-digital-5dbae.firebaseapp.com',
    storageBucket: 'comanda-digital-5dbae.firebasestorage.app',
  );

}